USE BlogDatabase;
GO

INSERT INTO Blog.Comment ([UserId],[ArticleId],[Body]) 
VALUES
	(73,47,'ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque.'),
	(5,84,'luctus lobortis. Class'),
	(1,70,'fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit'),
	(33,74,'ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus'),
	(13,55,'purus'),
	(55,36,'tempor augue ac ipsum. Phasellus'),
	(62,86,'Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec'),
	(9,8,'amet, risus. Donec nibh enim, gravida sit'),
	(43,7,'est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut,'),
	(99,8,'convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem'),
	(2,53,'Aliquam rutrum lorem ac'),
	(42,5,'non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin'),
	(35,41,'Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed'),
	(72,65,'feugiat metus sit amet'),
	(89,85,'semper cursus. Integer mollis. Integer tincidunt aliquam arcu.'),
	(93,92,'nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed'),
	(91,68,'eu'),
	(16,86,'Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin'),
	(2,73,'odio sagittis semper. Nam tempor diam'),
	(94,77,'pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi'),
	(37,98,'metus urna convallis erat, eget tincidunt dui augue eu tellus.'),
	(40,79,'sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis'),
	(41,30,'commodo ipsum. Suspendisse non leo. Vivamus'),
	(51,97,'ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere'),
	(63,99,'Curabitur ut odio vel est tempor bibendum.'),
	(53,6,'sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique'),
	(51,91,'luctus et'),
	(32,90,'Etiam vestibulum massa rutrum magna.'),
	(78,90,'vulputate, posuere vulputate, lacus.'),
	(76,15,'ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit,'),
	(93,92,'erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl.'),
	(93,39,'massa. Vestibulum accumsan neque'),
	(83,93,'luctus'),
	(91,80,'aliquet, sem ut cursus luctus, ipsum leo'),
	(10,25,'Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu.'),
	(40,100,'neque non quam.'),
	(47,92,'erat, eget'),
	(79,4,'malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac'),
	(94,60,'dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris'),
	(85,69,'aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In'),
	(55,91,'metus facilisis lorem'),
	(63,93,'est'),
	(5,31,'pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus'),
	(8,24,'et, lacinia vitae, sodales'),
	(92,19,'consectetuer'),
	(88,87,'sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque'),
	(94,36,'arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non,'),
	(58,78,'purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque'),
	(36,88,'quis, pede. Suspendisse dui. Fusce diam nunc,'),
	(39,26,'molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,'),
	(99,16,'libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat,'),
	(81,84,'adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio'),
	(65,54,'est tempor bibendum. Donec felis orci, adipiscing non,'),
	(75,71,'enim'),
	(71,95,'dis parturient montes, nascetur ridiculus mus.'),
	(87,41,'ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum'),
	(55,60,'urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,'),
	(83,94,'parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla'),
	(46,66,'augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut'),
	(80,61,'et magnis'),
	(35,22,'egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus'),
	(30,25,'orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula'),
	(85,8,'tempor arcu. Vestibulum ut eros non enim commodo hendrerit.'),
	(72,82,'Nullam lobortis quam a'),
	(31,78,'est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo'),
	(7,10,'vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie'),
	(18,93,'justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget'),
	(18,78,'tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse'),
	(97,52,'id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at'),
	(34,49,'enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida.'),
	(58,51,'tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum'),
	(18,34,'eget, dictum placerat, augue. Sed'),
	(13,78,'nascetur ridiculus mus.'),
	(91,52,'scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla'),
	(73,41,'erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras'),
	(45,60,'et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi'),
	(71,84,'magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero'),
	(96,72,'sit amet'),
	(85,30,'vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat'),
	(39,32,'lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis.'),
	(48,29,'penatibus'),
	(96,8,'imperdiet non, vestibulum nec, euismod in, dolor. Fusce'),
	(57,26,'consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae,'),
	(80,20,'Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin'),
	(45,60,'adipiscing, enim mi tempor lorem, eget mollis lectus pede'),
	(42,8,'sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat.'),
	(67,75,'viverra. Donec tempus, lorem fringilla ornare placerat,'),
	(6,16,'Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,'),
	(88,43,'et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse'),
	(51,80,'faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non'),
	(5,5,'magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit'),
	(8,20,'fringilla'),
	(25,53,'urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque'),
	(33,21,'nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque'),
	(10,75,'eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus'),
	(25,58,'Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien.'),
	(32,93,'orci luctus et ultrices'),
	(14,14,'imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.'),
	(35,9,'porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla'),
	(63,46,'justo. Proin non massa non ante bibendum');